def cr(c):
    if c == 'a': return 'n'
    elif c == 'b': return 'o'
    elif c == 'c': return 'p'
    elif c == 'd': return 'q'
    elif c == 'e': return 'r'
    elif c == 'f': return 's'
    elif c == 'g': return 't'
    elif c == 'h': return 'u'
    elif c == 'i': return 'v'
    elif c == 'j': return 'w'
    elif c == 'k': return 'x'
    elif c == 'l': return 'y'
    elif c == 'm': return 'z'
    elif c == 'n': return 'a'
    elif c == 'o': return 'b'
    elif c == 'p': return 'c'
    elif c == 'q': return 'd'
    elif c == 'r': return 'e'
    elif c == 's': return 'f'
    elif c == 't': return 'g'
    elif c == 'u': return 'h'
    elif c == 'v': return 'i'
    elif c == 'w': return 'j'
    elif c == 'x': return 'k'
    elif c == 'y': return 'l'
    elif c == 'z': return 'm'
    elif c == 'A': return 'N'
    elif c == 'B': return 'O'
    elif c == 'C': return 'P'
    elif c == 'D': return 'Q'
    elif c == 'E': return 'R'
    elif c == 'F': return 'S'
    elif c == 'G': return 'T'
    elif c == 'H': return 'U'
    elif c == 'I': return 'V'
    elif c == 'J': return 'W'
    elif c == 'K': return 'X'
    elif c == 'L': return 'Y'
    elif c == 'M': return 'Z'
    elif c == 'N': return 'A'
    elif c == 'O': return 'B'
    elif c == 'P': return 'C'
    elif c == 'Q': return 'D'
    elif c == 'R': return 'E'
    elif c == 'S': return 'F'
    elif c == 'T': return 'G'
    elif c == 'U': return 'H'
    elif c == 'V': return 'I'
    elif c == 'W': return 'J'
    elif c == 'X': return 'K'
    elif c == 'Y': return 'L'
    elif c == 'Z': return 'M'
    else: return c

while True:
    try:
        e = str(input())
        for i in range(len(e)):
            print(cr(e[i]), end='')
        print()
    except EOFError: break
